version: "3.9"
services:
  db:
    container_name: "asyncio-ch5-db"
    image: postgres:15.4
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"